repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - click>=8.1.6
          - pystac
          - pytest
          - types-aiofiles
          - types-python-dateutil
          - types-tabulate
          - types-tqdm
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.5"
    hooks:
      - id: ruff
      - id: ruff-format
